[build]
  command = "composer install && npm ci && npm run build && php artisan optimize"
  publish = "public"

[dev]
  command = "php artisan serve"
  port = 8888
  targetPort = 8000
  publish = "public"
  autoLaunch = true
  framework = "laravel"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
  force = true

[build.environment]
  PHP_VERSION = "8.3"
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Configuración específica para Laravel
[context.production.environment]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "errorlog"
  APP_KEY = "${APP_KEY}"
  DB_CONNECTION = "sqlite"
  CACHE_DRIVER = "array"
  SESSION_DRIVER = "array"
  QUEUE_DRIVER = "array"
